# Generated by Django 2.2.9 on 2022-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('usuario', models.CharField(max_length=100)),
                ('identificador', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('atualizacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
